/**
 * Master data for job preferences
 * Used in CAND-R02 Step 5: Job Preferences
 */

export const JOB_TYPES = [
  { value: 'full_time', label: 'Full-time (เต็มเวลา)' },
  { value: 'part_time', label: 'Part-time (พาร์ทไทม์)' },
  { value: 'contract', label: 'Contract (สัญญาจ้าง)' },
  { value: 'freelance', label: 'Freelance (อิสระ)' },
  { value: 'internship', label: 'Internship (ฝึกงาน)' },
] as const;

export const AVAILABILITY = [
  { value: 'immediate', label: 'ทันที' },
  { value: 'within_1_month', label: 'ภายใน 1 เดือน' },
  { value: 'within_3_months', label: 'ภายใน 3 เดือน' },
  { value: 'not_available', label: 'ยังไม่พร้อม' },
] as const;

// Thai provinces for work locations
export const PROVINCES = [
  "กรุงเทพมหานคร",
  "กระบี่",
  "กาญจนบุรี",
  "กาฬสินธุ์",
  "กำแพงเพชร",
  "ขอนแก่น",
  "จันทบุรี",
  "ฉะเชิงเทรา",
  "ชลบุรี",
  "ชัยนาท",
  "ชัยภูมิ",
  "ชุมพร",
  "เชียงราย",
  "เชียงใหม่",
  "ตรัง",
  "ตราด",
  "ตาก",
  "นครนายก",
  "นครปฐม",
  "นครพนม",
  "นครราชสีมา",
  "นครศรีธรรมราช",
  "นครสวรรค์",
  "นนทบุรี",
  "นราธิวาส",
  "น่าน",
  "บึงกาฬ",
  "บุรีรัมย์",
  "ปทุมธานี",
  "ประจวบคีรีขันธ์",
  "ปราจีนบุรี",
  "ปัตตานี",
  "พระนครศรีอยุธยา",
  "พังงา",
  "พัทลุง",
  "พิจิตร",
  "พิษณุโลก",
  "เพชรบุรี",
  "เพชรบูรณ์",
  "แพร่",
  "พะเยา",
  "ภูเก็ต",
  "มหาสารคาม",
  "มุกดาหาร",
  "แม่ฮ่องสอน",
  "ยะลา",
  "ยโสธร",
  "ร้อยเอ็ด",
  "ระนอง",
  "ระยอง",
  "ราชบุรี",
  "ลพบุรี",
  "ลำปาง",
  "ลำพูน",
  "เลย",
  "ศรีสะเกษ",
  "สกลนคร",
  "สงขลา",
  "สตูล",
  "สมุทรปราการ",
  "สมุทรสงคราม",
  "สมุทรสาคร",
  "สระแก้ว",
  "สระบุรี",
  "สิงห์บุรี",
  "สุโขทัย",
  "สุพรรณบุรี",
  "สุราษฎร์ธานี",
  "สุรินทร์",
  "หนองคาย",
  "หนองบัวลำภู",
  "อ่างทอง",
  "อำนาจเจริญ",
  "อุดรธานี",
  "อุตรดิตถ์",
  "อุทัยธานี",
  "อุบลราชธานี",
] as const;

export type JobType = typeof JOB_TYPES[number]['value'];
export type AvailabilityStatus = typeof AVAILABILITY[number]['value'];
export type Province = typeof PROVINCES[number];
