export const DEFAULT_CANDIDATE_DATA = {
  birthdate: 0,
  bloodgroup: "",
  birthplace: "",
  religion: "",
  nationality: "",
  race: "",
  height: 0,
  weight: 0,
  maritalStatus: "",
  millitaryStatus: "",
  email: "",
  phone: "",
  lineId: "",
  addressLine1: "",
  subDistrict: "",
  district: "",
  province: "",
  postCode: "",
  aboutMe: "",
  areaOfExpertise: "",
  achievement: "",
  hasCar: false,
  hasMotorcycle: false,
  referral: {
    referCode: "",
  },
  isActive: true,
  isSearchable: true,
  preference: {
    iAm: "",
    iAmLookingFor: [],
    iValues: [],
    myPreferredJobs: [],
    myValues: [],
    preferredCompany: "",
    preferredPosition: "",
    expectedSalary: 0,
    isNegotiable: false,
    headlines: "",
    overheadDays: "ทันที",
    expectedStartDate: 0,
    employment: "",
    jobType: "",
    jobFunction: "",
    jobIndustry: "",
  },
};
