export const DEFAULT_ACCOUNT_DATA = {
  uid: "",
  avatarURL: "",
  firstnameTH: "",
  lastnameTH: "",
  nicknameTH: "",
  firstnameEN: "",
  lastnameEN: "",
  nicknameEN: "",
  gender: "",
  isActive: true,
  serviceTypes: "",
  citizenId: "",
  jobTitle: "",
  addressLine1: "",
  subDistrict: "",
  district: "",
  city: "",
  province: "",
  postCode: "",
  phone: "",
  email: "",
  walletId: "",
};
